apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infrastructures.config.uccp.io
spec:
  group: config.uccp.io
  names:
    kind: Infrastructure
    listKind: InfrastructureList
    plural: infrastructures
    singular: infrastructure
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: config.uccp.io/v1
kind: Infrastructure
metadata:
  name: cluster
status:
  platform: kubemark
