apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
  namespace: uccp-machine-api
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        apiVersion: v1
        resource: namespace
        subresource: metrics
        namespace: uccp-machine-api

