apiVersion: config.uccp.io/v1
kind: ClusterOperator
metadata:
  name: machine-api
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
