apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-aws
  namespace: uccp-cloud-credential-operator
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - machine-api-controllers
  secretRef:
    name: aws-cloud-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:CreateTags
      - ec2:DescribeAvailabilityZones
      - ec2:DescribeDhcpOptions
      - ec2:DescribeImages
      - ec2:DescribeInstances
      - ec2:DescribeInternetGateways
      - ec2:DescribeSecurityGroups
      - ec2:DescribeSubnets
      - ec2:DescribeVpcs
      - ec2:RunInstances
      - ec2:TerminateInstances
      - elasticloadbalancing:DescribeLoadBalancers
      - elasticloadbalancing:DescribeTargetGroups
      - elasticloadbalancing:DescribeTargetHealth
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:RegisterTargets
      - elasticloadbalancing:DeregisterTargets
      - iam:PassRole
      - iam:CreateServiceLinkedRole
      resource: "*"
    - effect: Allow
      action:
      - kms:Decrypt
      - kms:Encrypt
      - kms:GenerateDataKey
      - kms:GenerateDataKeyWithoutPlainText
      - kms:DescribeKey
      resource: '*'
    - effect: Allow
      action:
      - kms:RevokeGrant
      - kms:CreateGrant
      - kms:ListGrants
      resource: '*'
      policyCondition:
        "Bool":
          "kms:GrantIsForAWSResource": true

---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-azure
  namespace: uccp-cloud-credential-operator
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: azure-cloud-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: AzureProviderSpec
    roleBindings:
    - role: Contributor
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-openstack
  namespace: uccp-cloud-credential-operator
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: openstack-cloud-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: OpenStackProviderSpec
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-gcp
  namespace: uccp-cloud-credential-operator
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - machine-api-controllers
  secretRef:
    name: gcp-cloud-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: GCPProviderSpec
    predefinedRoles:
    - "roles/compute.admin"
    - "roles/iam.serviceAccountUser"

---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-ovirt
  namespace: uccp-cloud-credential-operator
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: ovirt-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: OvirtProviderSpec
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-vsphere
  namespace: uccp-cloud-credential-operator
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: vsphere-cloud-credentials
    namespace: uccp-machine-api
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: VSphereProviderSpec
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-ibmcloud
  namespace: uccp-cloud-credential-operator
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: IBMCloudProviderSpec
    policies:
    - attributes:
      - name: serviceName
        value: is
      roles:
      - crn:v1:bluemix:public:iam::::role:Operator
      - crn:v1:bluemix:public:iam::::role:Editor
      - crn:v1:bluemix:public:iam::::role:Viewer
    - attributes:
      - name: resourceType
        value: resource-group
      roles:
      - crn:v1:bluemix:public:iam::::role:Viewer
  secretRef:
    namespace: uccp-machine-api
    name: ibmcloud-credentials
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: uccp-machine-api-powervs
  namespace: uccp-cloud-credential-operator
  annotations:
    include.release.uccp.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: IBMCloudPowerVSProviderSpec
    policies:
      - roles:
          - "crn:v1:bluemix:public:iam::::role:Viewer"
          - "crn:v1:bluemix:public:iam::::serviceRole:Reader"
          - "crn:v1:bluemix:public:iam::::serviceRole:Manager"
        attributes:
          - name: "serviceName"
            value: "power-iaas"
      - roles:
          - "crn:v1:bluemix:public:iam::::role:Viewer"
        attributes:
          - name: "resourceType"
            value: "resource-group"
  secretRef:
    namespace: uccp-machine-api
    name: powervs-credentials
---
apiVersion: cloudcredential.uccp.io/v1
kind: CredentialsRequest
metadata:
  name: uccp-machine-api-alibabacloud
  namespace: uccp-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.uccp.io/v1
    kind: AlibabaCloudProviderSpec
    statementEntries:
      - action:
        - ecs:DeleteInstances
        - ecs:DescribeImages
        - ecs:DescribeInstances
        - ecs:DescribeSecurityGroups
        - ecs:RunInstances
        - ecs:StopInstances
        - ecs:TagResources
        effect: Allow
        resource: '*'
      - action:
        - vpc:DescribeVpcs
        - vpc:DescribeVSwitches
        - ram:PassRole
        resource: '*'
        effect: Allow
  secretRef:
    namespace: uccp-machine-api
    name: alibabacloud-credentials
