apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: machine-api-operator-prometheus-rules
  namespace: uccp-machine-api
  annotations:
    exclude.release.uccp.io/internal-uccp-hosted: "true"
    include.release.uccp.io/self-managed-high-availability: "true"
    include.release.uccp.io/single-node-developer: "true"
spec:
  groups:
    - name: machine-without-valid-node-ref
      rules:
        - alert: MachineWithoutValidNode
          expr: |
             (mapi_machine_created_timestamp_seconds unless on(node) kube_node_info) > 0
          for: 60m
          labels:
            severity: warning
          annotations:
            message: "machine {{ $labels.name }} does not have valid node reference"
    - name: machine-with-no-running-phase
      rules:
        - alert: MachineWithNoRunningPhase
          expr: |
            (mapi_machine_created_timestamp_seconds{phase!~"Running|Deleting"}) > 0
          for: 60m
          labels:
            severity: warning
          annotations:
            message: "machine {{ $labels.name }} is in phase: {{ $labels.phase }}"
    - name: machine-not-yet-deleted
      rules:
        - alert: MachineNotYetDeleted
          expr: |
            (mapi_machine_created_timestamp_seconds{phase="Deleting"}) > 0
          for: 360m
          labels:
            severity: warning
          annotations:
            message: "machine {{ $labels.name }} has been in Deleting phase for more than 6 hours"
    - name: machine-api-operator-metrics-collector-up
      rules:
        - alert: MachineAPIOperatorMetricsCollectionFailing
          expr: |
             mapi_mao_collector_up == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            message: "machine api operator metrics collection is failing. For more details:  oc logs <machine-api-operator-pod-name> -n uccp-machine-api"
    - name: machine-health-check-unterminated-short-circuit
      rules:
        - alert: MachineHealthCheckUnterminatedShortCircuit
          expr: |
            mapi_machinehealthcheck_short_circuit == 1
          for: 30m
          labels:
            severity: warning
          annotation:
            message: "machine health check {{ $labels.name }} has been disabled by short circuit for more than 30 minutes"
